//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritingNumbers.DesktopClient.WriteNumberServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WriteNumberServiceReference.IWriteNumberService")]
    public interface IWriteNumberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWriteNumberService/ConvertNumberToWords", ReplyAction="http://tempuri.org/IWriteNumberService/ConvertNumberToWordsResponse")]
        string ConvertNumberToWords(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWriteNumberService/ConvertNumberToWords", ReplyAction="http://tempuri.org/IWriteNumberService/ConvertNumberToWordsResponse")]
        System.Threading.Tasks.Task<string> ConvertNumberToWordsAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWriteNumberServiceChannel : WritingNumbers.DesktopClient.WriteNumberServiceReference.IWriteNumberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WriteNumberServiceClient : System.ServiceModel.ClientBase<WritingNumbers.DesktopClient.WriteNumberServiceReference.IWriteNumberService>, WritingNumbers.DesktopClient.WriteNumberServiceReference.IWriteNumberService {
        
        public WriteNumberServiceClient() {
        }
        
        public WriteNumberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WriteNumberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WriteNumberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WriteNumberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertNumberToWords(string number) {
            return base.Channel.ConvertNumberToWords(number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertNumberToWordsAsync(string number) {
            return base.Channel.ConvertNumberToWordsAsync(number);
        }
    }
}
